Code optimization
mirage/ocaml-gpt pull request #7
Opened 2023-08-24 07:44 UTC by PizieDust

fixes #6 #5 #4

2023-08-24 07:47 UTC, PizieDust commented
cc @reynir

2023-08-24 08:08 UTC, reynir requested changes

2023-08-24 08:08 UTC, reynir commented on lib/gpt.mli
> +(* [make ?disk_guid disk_size sector_size partitions] constructs a GPT given a desired list of
```suggestion
(* [make ?disk_guid ~disk_size ~sector_size partitions] constructs a GPT given a desired list of
```

2023-08-24 08:08 UTC, reynir commented on test/test_gpt.ml
> +  let type_guid = Uuidm.v4_gen (Random.State.make_self_init ()) () in
Random values (without printing the seed) is not always a good idea. It makes the tests nondeterminstic. It's probably fine in our case since we don't inspect the uuid value. You can use:
```suggestion
  let type_guid = Option.get (Uuidm.of_string "12345678-1234-1234-1234-123456789abc") in 
```
`Option.get` is fine here because we know that `Uuidm.of_string` will not fail with this constant string.

2023-08-24 08:08 UTC, reynir commented on test/test_gpt.ml
> -
Yay! Code removed!

2023-08-24 08:42 UTC, PizieDust commented on test/test_gpt.ml
> +  let type_guid = Uuidm.v4_gen (Random.State.make_self_init ()) () in
Okay, thanks for the correction. I think this makes more sense too.

2023-09-15 08:04 UTC, reynir commented
Thanks!

2023-09-15 08:04 UTC, merged